import Link from "next/link";
import { ArrowLeft02Icon } from "@hugeicons/core-free-icons";
import { HugeiconsIcon } from "@hugeicons/react";

import { Button } from "@/components/ui/button";

interface TermsSection {
    title: string;
    subtitle?: string;
    content?: string[];
    list?: string[];
}

export const TERMS_OF_SERVICE: readonly TermsSection[] = [
    {
        title: "Acceptance of Terms",
        subtitle: "Contractual Agreement",
        content: [
            "By creating an account, accessing, or using dyit (the 'Service'), you explicitly agree to be bound by these Terms of Service, our Privacy Policy, and all applicable laws. These terms constitute a legally binding agreement between you and Dyit.",
            "If you are entering into this agreement on behalf of a company or legal entity, you represent that you have the authority to bind such entity. If you do not agree to these terms, you must immediately cease all use of the Service."
        ]
    },
    {
        title: "Eligibility and Account Security",
        subtitle: "User Responsibilities",
        content: [
            "You must be at least 13 years old (or the minimum legal age in your jurisdiction) to use this Service. You represent and warrant that all registration information you submit is truthful, accurate, and up to date.",
            "You are solely responsible for safeguarding the credentials associated with your account and for any activity or actions under your account. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account."
        ]
    },
    {
        title: "Acceptable Use Policy",
        subtitle: "Permitted Actions",
        content: [
            "Dyit provides tools for developer workflows and data automation. You are granted a limited, non-exclusive, non-transferable, and revocable license to use the Service strictly in accordance with these terms for personal or internal business operations."
        ]
    },
    {
        title: "Prohibited Activities",
        subtitle: "Strict Enforcement",
        list: [
            "Breaching, bypassing, or probing any security, authentication, or verification measures of the Service.",
            "Uploading, injecting, or transmitting malicious code, malware, viruses, or staging denial-of-service (DoS) attacks.",
            "Using the Service to infringe upon the intellectual property rights, privacy rights, or publicity rights of any third party.",
            "Scraping, crawling, or extracting data from the Service using automated systems without prior written authorization.",
            "Reverse engineering, decompiling, or attempting to derive the source code of the underlying infrastructure."
        ]
    },
    {
        title: "Intellectual Property and Content Ownership",
        subtitle: "Your Data and Our Platform",
        content: [
            "You retain all ownership, proprietary rights, and copyright to the code, text, data, and materials you upload or submit to the Service ('User Content'). By uploading content, you grant Dyit a worldwide, royalty-free, non-exclusive license to host, cache, store, transmit, and display your content solely to provide and maintain the Service.",
            "All text, graphics, user interfaces, visual interfaces, logos, code, software, and industrial designs generated by Dyit are the exclusive property of Dyit and are protected by international copyright, trademark, and trade secret laws."
        ]
    },
    {
        title: "Service Availability and Modifications",
        subtitle: "Uptime and Updates",
        content: [
            "While we strive for maximum platform reliability and uptime, the Service is provided on an 'AS IS' and 'AS AVAILABLE' basis. We do not guarantee that the service will be uninterrupted, entirely secure, or free from error.",
            "We reserve the right to modify, suspend, or discontinue any feature, API, or part of the Service at any time, with or without notice, to facilitate updates, safety protocols, or infrastructure maintenance."
        ]
    },
    {
        title: "Termination of Service",
        subtitle: "Account Suspension",
        content: [
            "We reserve the right, without liability and at our sole discretion, to suspend or terminate your access to the Service at any time, without prior notice, for conduct that we believe violates these Terms or is harmful to other users, public safety, or our business interests.",
            "Upon termination, your right to use the Service ceases immediately. You may request deletion of your account data in alignment with our operational data retention schedules."
        ]
    },
    {
        title: "Disclaimer of Warranties",
        subtitle: "No Guarantees",
        content: [
            "TO THE MAXIMUM EXTENT PERMITTED BY LAW, Dyit EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT."
        ]
    },
    {
        title: "Limitation of Liability",
        subtitle: "Financial Caps",
        content: [
            "TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL Dyit, ITS AFFILIATES, OFFICERS, OR LICENSORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES.",
            "IN NO EVENT SHALL OUR TOTAL AGGREGATE LIABILITY FOR ALL CLAIMS ARISING OUT OF OR RELATED TO THE USE OF THE SERVICE EXCEED THE GREATER OF ONE HUNDRED US DOLLARS ($100.00) OR THE TOTAL AMOUNT PAID BY YOU TO Dyit IN THE PAST TWELVE MONTHS."
        ]
    },
    {
        title: "Governing Law and Jurisdiction",
        subtitle: "Legal Resolution",
        content: [
            "These Terms shall be governed, construed, and enforced in accordance with the laws of the jurisdiction where Dyit operates its primary corporate headquarters, without regard to conflict of law principles.",
            "Any legal suit, action, or proceeding arising out of or related to these Terms shall be instituted exclusively in the federal or state courts located within our home jurisdiction, and you consent to personal jurisdiction in such courts."
        ]
    },
    {
        title: "Changes to These Terms",
        subtitle: "Revisions",
        content: [
            "We reserve the right to revise and amend these Terms periodically. We will post the updated version on this page and change the 'Last Updated' date at the top. For substantial changes, we will make reasonable efforts to notify you via email or platform announcements.",
            "Your continued use of Dyit following the effective date of any modifications indicates your explicit acknowledgment and acceptance of the revised Terms."
        ]
    },
    {
        title: "Contact Information",
        subtitle: "Support Channels",
        content: [
            "If you have any questions, concerns, or legal inquiries regarding these Terms of Service, please reach out to our team."
        ]
    }
] as const;

const LAST_UPDATED = "July 25, 2026";

export default function Terms() {
    return (
        <main className="mx-auto max-w-3xl px-4 py-8">
            <Button variant="secondary">
                <Link href="/" className="flex items-center gap-1">
                    <HugeiconsIcon icon={ArrowLeft02Icon} className="size-4" />
                    Back
                </Link>
            </Button>

            <header className="mb-8 mt-4 space-y-3 border-b border-border pb-4">
                <h1 className="font-space-grotesk-heading text-4xl font-bold tracking-tight">
                    Terms of Service
                </h1>

            </header>

            <div className="space-y-12">
                {TERMS_OF_SERVICE.map((section, index) => (
                    <section key={section.title} className="space-y-2">
                        <div className="flex items-center gap-4">
                            <span className="font-mono text-sm font-semibold text-muted-foreground">
                                {String(index + 1).padStart(2, "0")}
                            </span>

                            <div className="h-px flex-1 bg-border" />
                        </div>

                        <h2 className="font-space-grotesk-heading text-2xl font-semibold tracking-tight">
                            {section.title}
                        </h2>

                        {section.content?.map((paragraph) => (
                            <p
                                key={paragraph}
                                className="leading-6 text-muted-foreground"
                            >
                                {paragraph}
                            </p>
                        ))}

                        {section.list && (
                            <ul className="space-y-3 text-muted-foreground">
                                {section.list.map((item) => (
                                    <li key={item} className="flex gap-3">
                                        <span className="mt-2 size-1.5 rounded-full bg-primary shrink-0" />
                                        <span>{item}</span>
                                    </li>
                                ))}
                            </ul>
                        )}
                    </section>
                ))}

                <p className="text-sm text-muted-foreground">
                    Last updated: {LAST_UPDATED}
                </p>
            </div>
        </main>
    );
}